name: release-build

on:
  push:
    branches:
      - "*"

jobs:
  audit:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        path: 'cypress-recipe'

    - name: Checkout cypress
      uses: actions/checkout@v2
      with: 
        repository: 'projectcypress/cypress'
        path: 'cypress'

    - name: Set up Ruby
      uses: ruby/setup-ruby@b12138f02d7d0c4d36f463e0885dc47ec25a52fe
      with:
        ruby-version: 2.7.3

    - name: Provision Cookbook
      run: |
        ls
        cd cypress-recipe
        ls
        bundle install
        berks vendor cypress/contrib/cookbooks/
        cd ../cypress/contrib
        ls
    - name: Build AMI
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-var 'aws_access_key=${{secrets.AWS_ACCESS_KEY}}' -var 'aws_secret_key=${{secrets.AWS_SECRET_KEY}}' -var 'vpc_id=${{secrets.VPC_ID}}' -var 'subnet_id=${{secrets.SUBNET_ID}}' -only=cypress.amazonaws"
        target: cypress/contrib/cypress.json
